import { PERMISSIONS, PermissionDefinition } from '@schoolos/contracts';

export const PERMISSION_REGISTRY_METADATA: Record<string, PermissionDefinition> = {
  [PERMISSIONS.STUDENTS_READ]: {
    key: PERMISSIONS.STUDENTS_READ,
    domain: 'students',
    resource: 'Student',
    action: 'read',
    description: 'View student profiles, enrollments, and academic history',
    risk: 'LOW',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.STUDENTS_MANAGE]: {
    key: PERMISSIONS.STUDENTS_MANAGE,
    domain: 'students',
    resource: 'Student',
    action: 'manage',
    description: 'Create and update student profiles and enrollments',
    risk: 'MEDIUM',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.ATTENDANCE_READ]: {
    key: PERMISSIONS.ATTENDANCE_READ,
    domain: 'attendance',
    resource: 'Attendance',
    action: 'read',
    description: 'View daily and period attendance records',
    risk: 'LOW',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.ATTENDANCE_MANAGE]: {
    key: PERMISSIONS.ATTENDANCE_MANAGE,
    domain: 'attendance',
    resource: 'Attendance',
    action: 'manage',
    description: 'Mark and correct attendance for classes and sessions',
    risk: 'MEDIUM',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.FINANCE_READ]: {
    key: PERMISSIONS.FINANCE_READ,
    domain: 'finance',
    resource: 'Payment',
    action: 'read',
    description: 'View fee demands, payments, receipts, and invoices',
    risk: 'MEDIUM',
    sensitive: true,
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.FINANCE_COLLECT]: {
    key: PERMISSIONS.FINANCE_COLLECT,
    domain: 'finance',
    resource: 'Payment',
    action: 'collect',
    description: 'Collect student fee payments and generate receipts',
    risk: 'HIGH',
    sensitive: true,
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.FINANCE_REFUND]: {
    key: PERMISSIONS.FINANCE_REFUND,
    domain: 'finance',
    resource: 'Refund',
    action: 'refund',
    description: 'Issue fee refunds and concessions',
    risk: 'CRITICAL',
    sensitive: true,
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.ACADEMICS_READ]: {
    key: PERMISSIONS.ACADEMICS_READ,
    domain: 'academics',
    resource: 'Timetable',
    action: 'read',
    description: 'View classes, subjects, timetables, and homework',
    risk: 'LOW',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.EXAMS_READ]: {
    key: PERMISSIONS.EXAMS_READ,
    domain: 'exams',
    resource: 'Examination',
    action: 'read',
    description: 'View exam schedules, marks, and report cards',
    risk: 'LOW',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.SETTINGS_MANAGE]: {
    key: PERMISSIONS.SETTINGS_MANAGE,
    domain: 'settings',
    resource: 'SchoolSetting',
    action: 'manage',
    description: 'Manage school branding, settings, and integrations',
    risk: 'HIGH',
    sensitive: true,
    scopeType: 'SCHOOL',
  },
};
