import { PERMISSIONS, PermissionDefinition, SYSTEM_ROLES } from '@schoolos/contracts';

export const PERMISSION_REGISTRY_METADATA: Record<string, PermissionDefinition> = {
  [PERMISSIONS.STUDENTS_READ]: {
    key: PERMISSIONS.STUDENTS_READ,
    domain: 'students',
    resource: 'Student',
    action: 'read',
    description: 'View student profiles, enrollments, and academic history',
    risk: 'LOW',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.STUDENTS_MANAGE]: {
    key: PERMISSIONS.STUDENTS_MANAGE,
    domain: 'students',
    resource: 'Student',
    action: 'manage',
    description: 'Create and update student profiles and enrollments',
    risk: 'MEDIUM',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.ATTENDANCE_READ]: {
    key: PERMISSIONS.ATTENDANCE_READ,
    domain: 'attendance',
    resource: 'Attendance',
    action: 'read',
    description: 'View daily and period attendance records',
    risk: 'LOW',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.ATTENDANCE_MANAGE]: {
    key: PERMISSIONS.ATTENDANCE_MANAGE,
    domain: 'attendance',
    resource: 'Attendance',
    action: 'manage',
    description: 'Mark and correct attendance for classes and sessions',
    risk: 'MEDIUM',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.FINANCE_READ]: {
    key: PERMISSIONS.FINANCE_READ,
    domain: 'finance',
    resource: 'Payment',
    action: 'read',
    description: 'View fee demands, payments, receipts, and invoices',
    risk: 'MEDIUM',
    sensitive: true,
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.FINANCE_COLLECT]: {
    key: PERMISSIONS.FINANCE_COLLECT,
    domain: 'finance',
    resource: 'Payment',
    action: 'collect',
    description: 'Collect student fee payments and generate receipts',
    risk: 'HIGH',
    sensitive: true,
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.FINANCE_REFUND]: {
    key: PERMISSIONS.FINANCE_REFUND,
    domain: 'finance',
    resource: 'Refund',
    action: 'refund',
    description: 'Issue fee refunds and concessions',
    risk: 'CRITICAL',
    sensitive: true,
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.ACADEMICS_READ]: {
    key: PERMISSIONS.ACADEMICS_READ,
    domain: 'academics',
    resource: 'Timetable',
    action: 'read',
    description: 'View classes, subjects, timetables, and homework',
    risk: 'LOW',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.ACADEMICS_MANAGE]: {
    key: PERMISSIONS.ACADEMICS_MANAGE,
    domain: 'academics',
    resource: 'Timetable',
    action: 'manage',
    description: 'Manage timetables, class assignments, and homework',
    risk: 'MEDIUM',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.EXAMS_READ]: {
    key: PERMISSIONS.EXAMS_READ,
    domain: 'exams',
    resource: 'Examination',
    action: 'read',
    description: 'View exam schedules, marks, and report cards',
    risk: 'LOW',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.EXAMS_MANAGE]: {
    key: PERMISSIONS.EXAMS_MANAGE,
    domain: 'exams',
    resource: 'MarkEntry',
    action: 'manage',
    description: 'Enter marks, configure CBT exams, and create question banks',
    risk: 'MEDIUM',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.HR_READ]: {
    key: PERMISSIONS.HR_READ,
    domain: 'hr',
    resource: 'Employee',
    action: 'read',
    description: 'View staff directory and compliance reviews',
    risk: 'MEDIUM',
    sensitive: true,
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.HR_MANAGE]: {
    key: PERMISSIONS.HR_MANAGE,
    domain: 'hr',
    resource: 'Employee',
    action: 'manage',
    description: 'Manage staff profiles, contracts, and reviews',
    risk: 'HIGH',
    sensitive: true,
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.WORKFLOW_READ]: {
    key: PERMISSIONS.WORKFLOW_READ,
    domain: 'workflow',
    resource: 'WorkflowInstance',
    action: 'read',
    description: 'View pending workflow items and requisitions',
    risk: 'LOW',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.WORKFLOW_APPROVE]: {
    key: PERMISSIONS.WORKFLOW_APPROVE,
    domain: 'workflow',
    resource: 'WorkflowInstance',
    action: 'approve',
    description: 'Approve or reject workflow requisitions and requests',
    risk: 'HIGH',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.SECURITY_READ]: {
    key: PERMISSIONS.SECURITY_READ,
    domain: 'security',
    resource: 'Visitor',
    action: 'read',
    description: 'View visitor logs, pickups, and CCTV camera feeds',
    risk: 'LOW',
    scopeType: 'CAMPUS',
  },
  [PERMISSIONS.SECURITY_MANAGE]: {
    key: PERMISSIONS.SECURITY_MANAGE,
    domain: 'security',
    resource: 'Visitor',
    action: 'manage',
    description: 'Register visitors, release students, and manage CCTV',
    risk: 'MEDIUM',
    scopeType: 'CAMPUS',
  },
  [PERMISSIONS.SETTINGS_READ]: {
    key: PERMISSIONS.SETTINGS_READ,
    domain: 'settings',
    resource: 'SchoolSetting',
    action: 'read',
    description: 'View school configurations and settings',
    risk: 'LOW',
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.SETTINGS_MANAGE]: {
    key: PERMISSIONS.SETTINGS_MANAGE,
    domain: 'settings',
    resource: 'SchoolSetting',
    action: 'manage',
    description: 'Manage school branding, settings, and integrations',
    risk: 'HIGH',
    sensitive: true,
    scopeType: 'SCHOOL',
  },
  [PERMISSIONS.PLATFORM_READ]: {
    key: PERMISSIONS.PLATFORM_READ,
    domain: 'platform',
    resource: 'Platform',
    action: 'read',
    description: 'View multi-tenant platform metrics and audit logs',
    risk: 'HIGH',
    sensitive: true,
    scopeType: 'GLOBAL',
  },
  [PERMISSIONS.PLATFORM_MANAGE]: {
    key: PERMISSIONS.PLATFORM_MANAGE,
    domain: 'platform',
    resource: 'Platform',
    action: 'manage',
    description: 'Provision tenants, control feature flags, and support impersonation',
    risk: 'CRITICAL',
    sensitive: true,
    scopeType: 'GLOBAL',
  },
};

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  [SYSTEM_ROLES.PLATFORM_SUPER_ADMIN]: Object.values(PERMISSIONS),

  [SYSTEM_ROLES.ORGANIZATION_ADMIN]: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_COLLECT,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.ACADEMICS_READ,
    PERMISSIONS.ACADEMICS_MANAGE,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.EXAMS_MANAGE,
    PERMISSIONS.HR_READ,
    PERMISSIONS.HR_MANAGE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_APPROVE,
    PERMISSIONS.SECURITY_READ,
    PERMISSIONS.SECURITY_MANAGE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_MANAGE,
  ],

  [SYSTEM_ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_COLLECT,
    PERMISSIONS.ACADEMICS_READ,
    PERMISSIONS.ACADEMICS_MANAGE,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.EXAMS_MANAGE,
    PERMISSIONS.HR_READ,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_APPROVE,
    PERMISSIONS.SECURITY_READ,
    PERMISSIONS.SECURITY_MANAGE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_MANAGE,
  ],

  [SYSTEM_ROLES.PRINCIPAL]: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.ACADEMICS_READ,
    PERMISSIONS.ACADEMICS_MANAGE,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.EXAMS_PUBLISH,
    PERMISSIONS.HR_READ,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_APPROVE,
    PERMISSIONS.SECURITY_READ,
    PERMISSIONS.SETTINGS_READ,
  ],

  [SYSTEM_ROLES.TEACHER]: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ACADEMICS_READ,
    PERMISSIONS.ACADEMICS_MANAGE,
    PERMISSIONS.LMS_READ,
    PERMISSIONS.LMS_MANAGE,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.EXAMS_MANAGE,
  ],

  [SYSTEM_ROLES.ACCOUNTANT]: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_COLLECT,
    PERMISSIONS.ACCOUNTING_READ,
    PERMISSIONS.ACCOUNTING_MANAGE,
    PERMISSIONS.WORKFLOW_READ,
  ],

  [SYSTEM_ROLES.SECURITY_OFFICER]: [
    PERMISSIONS.SECURITY_READ,
    PERMISSIONS.SECURITY_MANAGE,
  ],

  [SYSTEM_ROLES.PARENT]: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ACADEMICS_READ,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.FINANCE_READ,
  ],

  [SYSTEM_ROLES.STUDENT]: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ACADEMICS_READ,
    PERMISSIONS.LMS_READ,
    PERMISSIONS.EXAMS_READ,
  ],
};
